version: '3.8'

services:
  api:
    build: "./backend"
    container_name: api
    env_file: "backend/.env"
    ports:
      - "3010:${PORT}"
  
  frontend:
    build: "./frontend"
    container_name: frontend
    env_file: "frontend/.env"
    ports:
      - "3000:3000"