version: '3.8'

services:
  api:
    build: "./backend"
    container_name: api
    env_file: 
      - "./backend/.env"
      - "./.env"
    ports:
      - 3010:${BACKEND_CONTAINER_PORT}
  
  frontend:
    build: "./frontend"
    container_name: frontend
    ports:
      - "3000:3000"